### ISSUE TITLE
Error Markdown 

### ISSUE THREAD

**Issue by yurbaez** [maestria-geotel-201902/unidad-0-asignacion-99-mi-proyecto-yurbaez#1]
@geofis 

Hola profe,

Estamos trabajando con el doc del markdown y me este error
![image](https://user-images.githubusercontent.com/39610484/72574772-9c836100-38a0-11ea-9afc-e2326db44ff9.png)

**Comment by yurbaez** [comment]
Ya funciona!!!

**Comment by geofis** [comment]
Imagino que estás trabajando en tu PC. Mejor que ya funcione.

**Comment by yurbaez** [comment]
Si trabajamos en la pc, pero volvió a dar el mismo error, al parecer es
prob de la conexión de Internet

Gracias
